adding a test to make sure you're able to successfully connect to the various mysql hosts before allowing the script to continue.
git-svn-id: svn+ssh://svn.wikimedia.org/svnroot/mediawiki/trunk@103089 dd0e9695-b195-4be7-bd10-2dea1a65a6b6

diff --git a/tools/switch-master/switch b/tools/switch-master/switch
--- a/tools/switch-master/switch
+++ b/tools/switch-master/switch
@@ -10,9 +10,27 @@ cd $dir
 
 . config
 
+
 echo Current master: $master
 echo New master: $newmaster
 echo "Slaves (must not contain either of the above): $slaves"
+# testing to make sure we can connect to mysql on the master and slaves
+for i in $master $newmaster $slaves
+do
+	echo -n "checking mysql connection to $i... "
+	mysql -h $i -e 'select 1' > /dev/null
+	ret=$?
+	if [ $ret -ne 0 ]
+	then
+		echo "failed!"
+		echo "Please make it so 'mysql -h $i' will work."
+		echo "Bailing out."
+		exit 1
+	else
+		echo "done."
+	fi
+done
+
 pause "Ready? Press enter to continue, or ctrl-c to exit"
 
 echo "Setting master to read only..."
